/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package METODE;
import static METODE.MathParsing.MathParsing;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author MuhammadAlham
 */
public class gui extends javax.swing.JFrame {

    /**
     * Creates new form gui
     */
    public gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tabMetode = new javax.swing.JTabbedPane();
        tabAitken = new javax.swing.JPanel();
        tabBiseksi = new javax.swing.JPanel();
        tabIterasi = new javax.swing.JPanel();
        inputIterasi = new javax.swing.JPanel();
        label4 = new javax.swing.JLabel();
        inFxIterasi = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        inGxIterasi = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        inIterasiIterasi = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        inErrorIterasi = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        inBatasatasIterasi = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        inBatasbawahIterasi = new javax.swing.JTextField();
        outputIterasi = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tProsesIterasi = new javax.swing.JTable();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        scrollpane2 = new javax.swing.JScrollPane();
        hAkhirIterasi = new javax.swing.JTextPane();
        jPanel7 = new javax.swing.JPanel();
        btnClearIterasi = new javax.swing.JButton();
        btnCariIterasi = new javax.swing.JButton();
        btnSimpanIterasi = new javax.swing.JButton();
        tabMuller = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnClearMuller = new javax.swing.JButton();
        btnCariMuller = new javax.swing.JButton();
        btnSimpanMuller = new javax.swing.JButton();
        output2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tProsesMuller = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        scrollpane1 = new javax.swing.JScrollPane();
        hAkhirMuller = new javax.swing.JTextPane();
        inputMuller = new javax.swing.JPanel();
        label3 = new javax.swing.JLabel();
        inFxMuller = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        inIterasiMuller = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        inErrorMuller = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        inX0Muller = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        inX1Muller = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        inX2Muller = new javax.swing.JTextField();
        tabNR = new javax.swing.JPanel();
        tabRF = new javax.swing.JPanel();
        input1 = new javax.swing.JPanel();
        label2 = new javax.swing.JLabel();
        inFxRF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        inIterasiRF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        inErrorRF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        inBatasbawahRF = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        inBatasatasRF = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        output1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tProsesRF = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        scrollpane = new javax.swing.JScrollPane();
        hAkhirRF = new javax.swing.JTextPane();
        jPanel5 = new javax.swing.JPanel();
        btnClearRF = new javax.swing.JButton();
        btnCariRF = new javax.swing.JButton();
        btnSimpanRF = new javax.swing.JButton();
        tabSecant = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("METODE APROKSIMASI");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(2000, 440));

        tabMetode.setBackground(new java.awt.Color(0, 0, 0));
        tabMetode.setForeground(new java.awt.Color(25, 71, 138));
        tabMetode.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        tabMetode.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        tabMetode.setName("AITKEN"); // NOI18N
        tabMetode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabMetodeMouseClicked(evt);
            }
        });

        tabAitken.setBackground(new java.awt.Color(153, 153, 153));
        tabAitken.setAutoscrolls(true);
        tabAitken.setFont(new java.awt.Font("Megalomania", 0, 11)); // NOI18N

        javax.swing.GroupLayout tabAitkenLayout = new javax.swing.GroupLayout(tabAitken);
        tabAitken.setLayout(tabAitkenLayout);
        tabAitkenLayout.setHorizontalGroup(
            tabAitkenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 864, Short.MAX_VALUE)
        );
        tabAitkenLayout.setVerticalGroup(
            tabAitkenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        tabMetode.addTab("AITKEN", new javax.swing.ImageIcon(getClass().getResource("/image/icon/gears.png")), tabAitken, ""); // NOI18N

        tabBiseksi.setBackground(new java.awt.Color(153, 153, 153));
        tabBiseksi.setFont(new java.awt.Font("Megalomania", 0, 11)); // NOI18N

        javax.swing.GroupLayout tabBiseksiLayout = new javax.swing.GroupLayout(tabBiseksi);
        tabBiseksi.setLayout(tabBiseksiLayout);
        tabBiseksiLayout.setHorizontalGroup(
            tabBiseksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 864, Short.MAX_VALUE)
        );
        tabBiseksiLayout.setVerticalGroup(
            tabBiseksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        tabMetode.addTab("BISEKSI", new javax.swing.ImageIcon(getClass().getResource("/image/icon/gears.png")), tabBiseksi); // NOI18N

        tabIterasi.setBackground(new java.awt.Color(153, 153, 153));
        tabIterasi.setFont(new java.awt.Font("Megalomania", 0, 11)); // NOI18N

        inputIterasi.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INPUT", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        label4.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        label4.setForeground(new java.awt.Color(25, 71, 138));
        label4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label4.setText("f(x)");
        label4.setAlignmentX(0.5F);
        label4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        inFxIterasi.setToolTipText("Masukan Fungsi (contoh : x^2)");
        inFxIterasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inFxIterasiActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(25, 71, 138));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText("g(x)");

        inGxIterasi.setToolTipText("");
        inGxIterasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inGxIterasiActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(25, 71, 138));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel23.setText("Maksimal Iterasi");

        inIterasiIterasi.setToolTipText("Error yang dapat ditoleransi");
        inIterasiIterasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inIterasiIterasiActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(25, 71, 138));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel24.setText("Error");

        inErrorIterasi.setToolTipText("");
        inErrorIterasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inErrorIterasiActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(25, 71, 138));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel25.setText("Batas Atas (a)");

        inBatasatasIterasi.setToolTipText("");
        inBatasatasIterasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inBatasatasIterasiActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(25, 71, 138));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel29.setText("Batas Bawah (b)");

        inBatasbawahIterasi.setToolTipText("");
        inBatasbawahIterasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inBatasbawahIterasiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inputIterasiLayout = new javax.swing.GroupLayout(inputIterasi);
        inputIterasi.setLayout(inputIterasiLayout);
        inputIterasiLayout.setHorizontalGroup(
            inputIterasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(inputIterasiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputIterasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inputIterasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                        .addComponent(label4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inputIterasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inFxIterasi)
                    .addComponent(inGxIterasi)
                    .addGroup(inputIterasiLayout.createSequentialGroup()
                        .addGroup(inputIterasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(inputIterasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(inBatasatasIterasi, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(inErrorIterasi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(inIterasiIterasi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(inBatasbawahIterasi, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        inputIterasiLayout.setVerticalGroup(
            inputIterasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputIterasiLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(inputIterasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(inFxIterasi, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(inputIterasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inGxIterasi, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(inputIterasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inputIterasiLayout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(inputIterasiLayout.createSequentialGroup()
                        .addComponent(inIterasiIterasi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inErrorIterasi, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inBatasatasIterasi, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inBatasbawahIterasi)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        inputIterasiLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {inBatasatasIterasi, inBatasbawahIterasi, inErrorIterasi, inFxIterasi, inGxIterasi, inIterasiIterasi});

        outputIterasi.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "OUTPUT", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        tProsesIterasi.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        tProsesIterasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "n", "xn", "x(n+1)"
            }
        ));
        tProsesIterasi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tProsesIterasi.setRequestFocusEnabled(false);
        tProsesIterasi.setRowHeight(20);
        tProsesIterasi.setRowSelectionAllowed(false);
        tProsesIterasi.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(tProsesIterasi);

        jLabel27.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(25, 71, 138));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("PROSES ITERASI");

        jLabel28.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Solusi Akhir");

        hAkhirIterasi.setEditable(false);
        scrollpane2.setViewportView(hAkhirIterasi);

        javax.swing.GroupLayout outputIterasiLayout = new javax.swing.GroupLayout(outputIterasi);
        outputIterasi.setLayout(outputIterasiLayout);
        outputIterasiLayout.setHorizontalGroup(
            outputIterasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outputIterasiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(outputIterasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(outputIterasiLayout.createSequentialGroup()
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(scrollpane2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        outputIterasiLayout.setVerticalGroup(
            outputIterasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outputIterasiLayout.createSequentialGroup()
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                .addGap(15, 15, 15)
                .addGroup(outputIterasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addComponent(scrollpane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        jPanel7.setBackground(new java.awt.Color(35, 141, 205));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, new java.awt.Color(0, 102, 255)));

        btnClearIterasi.setBackground(new java.awt.Color(204, 204, 204));
        btnClearIterasi.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        btnClearIterasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/waste.png"))); // NOI18N
        btnClearIterasi.setText("CLEAR");
        btnClearIterasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearIterasiActionPerformed(evt);
            }
        });

        btnCariIterasi.setBackground(new java.awt.Color(204, 204, 204));
        btnCariIterasi.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        btnCariIterasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/calculator.png"))); // NOI18N
        btnCariIterasi.setText("CARI");
        btnCariIterasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariIterasiActionPerformed(evt);
            }
        });

        btnSimpanIterasi.setBackground(new java.awt.Color(204, 204, 204));
        btnSimpanIterasi.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        btnSimpanIterasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/save.png"))); // NOI18N
        btnSimpanIterasi.setText("SIMPAN");
        btnSimpanIterasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanIterasiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(btnClearIterasi, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnCariIterasi, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnSimpanIterasi, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addGap(87, 87, 87))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClearIterasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCariIterasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSimpanIterasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout tabIterasiLayout = new javax.swing.GroupLayout(tabIterasi);
        tabIterasi.setLayout(tabIterasiLayout);
        tabIterasiLayout.setHorizontalGroup(
            tabIterasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabIterasiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabIterasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(tabIterasiLayout.createSequentialGroup()
                        .addComponent(inputIterasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(outputIterasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tabIterasiLayout.setVerticalGroup(
            tabIterasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabIterasiLayout.createSequentialGroup()
                .addGroup(tabIterasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(outputIterasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputIterasi, javax.swing.GroupLayout.PREFERRED_SIZE, 404, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        tabMetode.addTab("ITERASI", new javax.swing.ImageIcon(getClass().getResource("/image/icon/gears.png")), tabIterasi); // NOI18N

        tabMuller.setBackground(new java.awt.Color(153, 153, 153));
        tabMuller.setFont(new java.awt.Font("Megalomania", 0, 11)); // NOI18N

        jPanel6.setBackground(new java.awt.Color(35, 141, 205));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, new java.awt.Color(0, 102, 255)));

        btnClearMuller.setBackground(new java.awt.Color(204, 204, 204));
        btnClearMuller.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        btnClearMuller.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/waste.png"))); // NOI18N
        btnClearMuller.setText("CLEAR");
        btnClearMuller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearMullerActionPerformed(evt);
            }
        });

        btnCariMuller.setBackground(new java.awt.Color(204, 204, 204));
        btnCariMuller.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        btnCariMuller.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/calculator.png"))); // NOI18N
        btnCariMuller.setText("CARI");
        btnCariMuller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariMullerActionPerformed(evt);
            }
        });

        btnSimpanMuller.setBackground(new java.awt.Color(204, 204, 204));
        btnSimpanMuller.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        btnSimpanMuller.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/save.png"))); // NOI18N
        btnSimpanMuller.setText("SIMPAN");
        btnSimpanMuller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanMullerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(btnClearMuller, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnCariMuller, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnSimpanMuller, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addGap(87, 87, 87))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClearMuller, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCariMuller, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSimpanMuller, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        output2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "OUTPUT", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        tProsesMuller.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        tProsesMuller.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "n", "X0", "X1", "X2", "f(x2)"
            }
        ));
        tProsesMuller.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tProsesMuller.setRequestFocusEnabled(false);
        tProsesMuller.setRowHeight(20);
        tProsesMuller.setRowSelectionAllowed(false);
        tProsesMuller.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(tProsesMuller);

        jLabel14.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(25, 71, 138));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("PROSES ITERASI");

        jLabel15.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Solusi Akhir");

        hAkhirMuller.setEditable(false);
        scrollpane1.setViewportView(hAkhirMuller);

        javax.swing.GroupLayout output2Layout = new javax.swing.GroupLayout(output2);
        output2.setLayout(output2Layout);
        output2Layout.setHorizontalGroup(
            output2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(output2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(output2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(output2Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(scrollpane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        output2Layout.setVerticalGroup(
            output2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(output2Layout.createSequentialGroup()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                .addGap(15, 15, 15)
                .addGroup(output2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(scrollpane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        inputMuller.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INPUT", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        label3.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        label3.setForeground(new java.awt.Color(25, 71, 138));
        label3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label3.setText("F(x)");
        label3.setAlignmentX(0.5F);
        label3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        inFxMuller.setToolTipText("Masukan Fungsi (contoh : x^2)");
        inFxMuller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inFxMullerActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(25, 71, 138));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Maksimal Iterasi");

        inIterasiMuller.setToolTipText("");
        inIterasiMuller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inIterasiMullerActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(25, 71, 138));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Error");

        inErrorMuller.setToolTipText("Error yang dapat ditoleransi");
        inErrorMuller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inErrorMullerActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(25, 71, 138));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("X0");

        inX0Muller.setToolTipText("");
        inX0Muller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inX0MullerActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(25, 71, 138));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("X1");

        inX1Muller.setToolTipText("");
        inX1Muller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inX1MullerActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(25, 71, 138));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("X2");

        inX2Muller.setToolTipText("");
        inX2Muller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inX2MullerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inputMullerLayout = new javax.swing.GroupLayout(inputMuller);
        inputMuller.setLayout(inputMullerLayout);
        inputMullerLayout.setHorizontalGroup(
            inputMullerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(inputMullerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputMullerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(label3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inputMullerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inFxMuller)
                    .addComponent(inIterasiMuller)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inputMullerLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(inErrorMuller, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(inputMullerLayout.createSequentialGroup()
                        .addGroup(inputMullerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inX0Muller, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inX1Muller, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inX2Muller, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        inputMullerLayout.setVerticalGroup(
            inputMullerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputMullerLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(inputMullerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(inFxMuller, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(inputMullerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inIterasiMuller, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(inputMullerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inErrorMuller))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(inputMullerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inX0Muller, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(inputMullerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(inX1Muller, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addGroup(inputMullerLayout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(inputMullerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inputMullerLayout.createSequentialGroup()
                        .addComponent(inX2Muller, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        inputMullerLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {inErrorMuller, inFxMuller, inIterasiMuller, inX0Muller, inX1Muller, inX2Muller});

        javax.swing.GroupLayout tabMullerLayout = new javax.swing.GroupLayout(tabMuller);
        tabMuller.setLayout(tabMullerLayout);
        tabMullerLayout.setHorizontalGroup(
            tabMullerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabMullerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabMullerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(tabMullerLayout.createSequentialGroup()
                        .addComponent(inputMuller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(output2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tabMullerLayout.setVerticalGroup(
            tabMullerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabMullerLayout.createSequentialGroup()
                .addGroup(tabMullerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(output2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputMuller, javax.swing.GroupLayout.PREFERRED_SIZE, 404, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        tabMetode.addTab("MULLER", new javax.swing.ImageIcon(getClass().getResource("/image/icon/gears.png")), tabMuller); // NOI18N

        tabNR.setBackground(new java.awt.Color(153, 153, 153));
        tabNR.setFont(new java.awt.Font("Megalomania", 0, 11)); // NOI18N

        javax.swing.GroupLayout tabNRLayout = new javax.swing.GroupLayout(tabNR);
        tabNR.setLayout(tabNRLayout);
        tabNRLayout.setHorizontalGroup(
            tabNRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 864, Short.MAX_VALUE)
        );
        tabNRLayout.setVerticalGroup(
            tabNRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        tabMetode.addTab("NEWTON RAHPSON", new javax.swing.ImageIcon(getClass().getResource("/image/icon/gears.png")), tabNR); // NOI18N

        tabRF.setBackground(new java.awt.Color(153, 153, 153));
        tabRF.setFont(new java.awt.Font("Megalomania", 0, 11)); // NOI18N

        input1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INPUT", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        label2.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        label2.setForeground(new java.awt.Color(25, 71, 138));
        label2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label2.setText("F(x)");
        label2.setAlignmentX(0.5F);
        label2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        inFxRF.setToolTipText("Masukan Fungsi (contoh : x^2)");
        inFxRF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inFxRFActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(25, 71, 138));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Maksimal Iterasi");

        inIterasiRF.setToolTipText("");
        inIterasiRF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inIterasiRFActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(25, 71, 138));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Error");

        inErrorRF.setToolTipText("Error yang dapat ditoleransi");
        inErrorRF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inErrorRFActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(25, 71, 138));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Batas Bawah (a)");

        inBatasbawahRF.setToolTipText("");
        inBatasbawahRF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inBatasbawahRFActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(25, 71, 138));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Batas Atas (b)");

        inBatasatasRF.setToolTipText("");
        inBatasatasRF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inBatasatasRFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout input1Layout = new javax.swing.GroupLayout(input1);
        input1.setLayout(input1Layout);
        input1Layout.setHorizontalGroup(
            input1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(input1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(input1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(input1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inFxRF)
                    .addComponent(inIterasiRF)
                    .addComponent(inErrorRF, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inBatasbawahRF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inBatasatasRF, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        input1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {inBatasatasRF, inBatasbawahRF});

        input1Layout.setVerticalGroup(
            input1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(input1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(input1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(inFxRF, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(input1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inIterasiRF, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(input1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inErrorRF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(input1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inBatasbawahRF, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(input1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inBatasatasRF, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        input1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {inBatasatasRF, inBatasbawahRF, inErrorRF, inFxRF, inIterasiRF});

        output1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "OUTPUT", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        tProsesRF.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        tProsesRF.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "i", "a", "b", "x", "Fa", "Fb", "Fx"
            }
        ));
        tProsesRF.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tProsesRF.setRequestFocusEnabled(false);
        tProsesRF.setRowHeight(20);
        tProsesRF.setRowSelectionAllowed(false);
        tProsesRF.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tProsesRF);
        if (tProsesRF.getColumnModel().getColumnCount() > 0) {
            tProsesRF.getColumnModel().getColumn(3).setHeaderValue("x");
            tProsesRF.getColumnModel().getColumn(4).setHeaderValue("Fa");
            tProsesRF.getColumnModel().getColumn(5).setHeaderValue("Fb");
            tProsesRF.getColumnModel().getColumn(6).setHeaderValue("Fx");
        }

        jLabel10.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(25, 71, 138));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("PROSES ITERASI");

        jLabel11.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Solusi Akhir");

        hAkhirRF.setEditable(false);
        scrollpane.setViewportView(hAkhirRF);

        javax.swing.GroupLayout output1Layout = new javax.swing.GroupLayout(output1);
        output1.setLayout(output1Layout);
        output1Layout.setHorizontalGroup(
            output1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(output1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(output1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(output1Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(scrollpane, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        output1Layout.setVerticalGroup(
            output1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(output1Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                .addGap(15, 15, 15)
                .addGroup(output1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(scrollpane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        jPanel5.setBackground(new java.awt.Color(35, 141, 205));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, new java.awt.Color(0, 102, 255)));

        btnClearRF.setBackground(new java.awt.Color(204, 204, 204));
        btnClearRF.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        btnClearRF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/waste.png"))); // NOI18N
        btnClearRF.setText("CLEAR");
        btnClearRF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearRFActionPerformed(evt);
            }
        });

        btnCariRF.setBackground(new java.awt.Color(204, 204, 204));
        btnCariRF.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        btnCariRF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/calculator.png"))); // NOI18N
        btnCariRF.setText("CARI");
        btnCariRF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariRFActionPerformed(evt);
            }
        });

        btnSimpanRF.setBackground(new java.awt.Color(204, 204, 204));
        btnSimpanRF.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        btnSimpanRF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/save.png"))); // NOI18N
        btnSimpanRF.setText("SIMPAN");
        btnSimpanRF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanRFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(btnClearRF, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnCariRF, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnSimpanRF, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addGap(87, 87, 87))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClearRF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCariRF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSimpanRF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout tabRFLayout = new javax.swing.GroupLayout(tabRF);
        tabRF.setLayout(tabRFLayout);
        tabRFLayout.setHorizontalGroup(
            tabRFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabRFLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabRFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(tabRFLayout.createSequentialGroup()
                        .addComponent(input1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(output1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tabRFLayout.setVerticalGroup(
            tabRFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabRFLayout.createSequentialGroup()
                .addGroup(tabRFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(output1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(input1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        tabMetode.addTab("REGULAR FALSI", new javax.swing.ImageIcon(getClass().getResource("/image/icon/gears.png")), tabRF); // NOI18N

        javax.swing.GroupLayout tabSecantLayout = new javax.swing.GroupLayout(tabSecant);
        tabSecant.setLayout(tabSecantLayout);
        tabSecantLayout.setHorizontalGroup(
            tabSecantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 864, Short.MAX_VALUE)
        );
        tabSecantLayout.setVerticalGroup(
            tabSecantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        tabMetode.addTab("SECANT", new javax.swing.ImageIcon(getClass().getResource("/image/icon/gears.png")), tabSecant); // NOI18N

        jPanel2.setBackground(new java.awt.Color(35, 141, 205));

        jLabel1.setFont(new java.awt.Font("Space Age", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ribbon.png"))); // NOI18N
        jLabel1.setText("METODE APROKSIMASI");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(25, 71, 138), null));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabMetode)
                .addContainerGap())
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabMetode, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE))
        );

        tabMetode.getAccessibleContext().setAccessibleName("AITKEN");

        jMenuBar1.setBackground(new java.awt.Color(25, 71, 138));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(25, 71, 138)));
        jMenuBar1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        jMenu1.setText("Program");
        jMenu1.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/home16.png"))); // NOI18N
        jMenuItem3.setText("Beranda");
        jMenuItem3.setPreferredSize(new java.awt.Dimension(90, 30));
        jMenu1.add(jMenuItem3);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/delete.png"))); // NOI18N
        jMenuItem1.setText("Exit");
        jMenuItem1.setPreferredSize(new java.awt.Dimension(90, 30));
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Bantuan");
        jMenu2.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/info.png"))); // NOI18N
        jMenuItem2.setText("Tentang");
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1058, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
                .addGap(11, 11, 11))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tabMetodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabMetodeMouseClicked

    }//GEN-LAST:event_tabMetodeMouseClicked

    private void inFxRFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inFxRFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inFxRFActionPerformed

    private void inIterasiRFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inIterasiRFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inIterasiRFActionPerformed

    private void inErrorRFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inErrorRFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inErrorRFActionPerformed

    private void inBatasbawahRFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inBatasbawahRFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inBatasbawahRFActionPerformed

    private void btnCariRFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariRFActionPerformed
        double Fa,Fb,Fx,x = 0;
     String fx=inFxRF.getText();
     int n= Integer.parseInt(inIterasiRF.getText());
     double a= Double.parseDouble(inBatasbawahRF.getText());
     double b= Double.parseDouble(inBatasatasRF.getText());
     double tlrn= Double.parseDouble(inErrorRF.getText());
     while(true){
     if(MathParsing(fx,a)*MathParsing(fx,b)<=0) break; //6. Jika Fa*Fb<=0 berarti a<=solusi<=b
            //if(MathParsing(fx,a)*MathParsing(fx,b)>0) System.out.println("Pilih interval a<solusi<b");
     }
     Fa=MathParsing(fx,a);
     Fb=MathParsing(fx,b);
        DefaultTableModel model=(DefaultTableModel) tProsesRF.getModel();
            while(model.getRowCount()>0)
            {
                    for(int i=0;i<model.getRowCount();i++)
                    {
                        model.removeRow(i);
                    }
            }
                for(int i=0;i<n;i++)
                {
                    x=(a*Fb-b*Fa)/(Fb-Fa);
                    Fx=MathParsing(fx,x);
                                
                        model.addRow(new Object[]
                        {
                                i+1,a,b,x,Fa,Fb,Fx
                        });
            
            if(Math.abs(Fx)<tlrn) break;
            if(Fx*Fa<0)
            {
                b=x;
                Fb=Fx;
            } 
            else
            {
                a=x;
                Fa=Fx;
            }
        }
     String outputRF = String.valueOf(x);
     hAkhirRF.setText(outputRF);
    }//GEN-LAST:event_btnCariRFActionPerformed

    private void btnSimpanRFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanRFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanRFActionPerformed

    private void inBatasatasRFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inBatasatasRFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inBatasatasRFActionPerformed

    private void btnClearRFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearRFActionPerformed
        DefaultTableModel model=(DefaultTableModel) tProsesRF.getModel();
        while(model.getRowCount()>0){
                    for(int i=0;i<model.getRowCount();i++){
                        model.removeRow(i);
                    }
                }
    }//GEN-LAST:event_btnClearRFActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnClearMullerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearMullerActionPerformed
        DefaultTableModel model=(DefaultTableModel) tProsesRF.getModel();
        while(model.getRowCount()>0){
                    for(int i=0;i<model.getRowCount();i++){
                        model.removeRow(i);
                    }
                }
    }//GEN-LAST:event_btnClearMullerActionPerformed

    private void btnCariMullerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariMullerActionPerformed
     double h0,h1,d0,d1,a,b,c,h,Fx0,Fx1,Fx2,x0,x1,x2,xhasil = 0;
     String fx=inFxMuller.getText();
     int n= Integer.parseInt(inIterasiMuller.getText());
     double tlrn= Double.parseDouble(inErrorMuller.getText());
     x0= Double.parseDouble(inX0Muller.getText());
     x1= Double.parseDouble(inX1Muller.getText());
     x2= Double.parseDouble(inX2Muller.getText());
     DefaultTableModel model=(DefaultTableModel) tProsesMuller.getModel();
     

//untuk clear tabel
               
     while(model.getRowCount()>0)
            {
                    for(int j=0;j<model.getRowCount();j++)
                    {
                        model.removeRow(j);
                    }
            }
           
     //methodMuller
        for(int i=0;i<n;i++){
            Fx0=MathParsing(fx,x0);
            Fx1=MathParsing(fx,x1);
            Fx2=MathParsing(fx,x2);
            
            h0=x1-x0;
            h1=x2-x1;
            d0=(Fx1-Fx0)/(x1-x0);
            d1=(Fx2-Fx1)/(x2-x1);
            a=(d1-d0)/(h1+h0);
            b=a*h1+d1;
            c=Fx2;
            
            double D = Math.sqrt(b*b-4*a*c);
            if (Math.abs(b-D)<Math.abs(b+D)) 
                h=(-2*c)/(b+D);
            else h=(-2*c)/(b-D);
            
            xhasil=x2+h;
            double math=MathParsing(fx,xhasil);
            //System.out.printf(i+"\t%.4f\t%.4f\t%.4f\t%.4f\n",x0,x1,x2,MathParsing(function,xhasil));
            
        
     model.addRow(new Object[]
                        {
                                i,x0,x1,x2,math
                        });
            
     if (Math.abs(MathParsing(fx,xhasil))<tlrn) break;
            else {
                x0=x1;
                x1=x2;
                x2=xhasil;
            }
     
        }
     String outputMuller = String.valueOf(xhasil);
     hAkhirMuller.setText(outputMuller);  
     
    }//GEN-LAST:event_btnCariMullerActionPerformed

    private void btnSimpanMullerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanMullerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanMullerActionPerformed

    private void inFxMullerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inFxMullerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inFxMullerActionPerformed

    private void inIterasiMullerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inIterasiMullerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inIterasiMullerActionPerformed

    private void inErrorMullerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inErrorMullerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inErrorMullerActionPerformed

    private void inX0MullerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inX0MullerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inX0MullerActionPerformed

    private void inX1MullerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inX1MullerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inX1MullerActionPerformed

    private void inX2MullerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inX2MullerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inX2MullerActionPerformed

    private void inFxIterasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inFxIterasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inFxIterasiActionPerformed

    private void inGxIterasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inGxIterasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inGxIterasiActionPerformed

    private void inIterasiIterasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inIterasiIterasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inIterasiIterasiActionPerformed

    private void inErrorIterasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inErrorIterasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inErrorIterasiActionPerformed

    private void inBatasatasIterasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inBatasatasIterasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inBatasatasIterasiActionPerformed

    private void inBatasbawahIterasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inBatasbawahIterasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inBatasbawahIterasiActionPerformed

    private void btnSimpanIterasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanIterasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanIterasiActionPerformed

    private void btnCariIterasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariIterasiActionPerformed

    }//GEN-LAST:event_btnCariIterasiActionPerformed

    private void btnClearIterasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearIterasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearIterasiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    try {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    } catch (IllegalAccessException ex) {
                        Logger.getLogger(gui.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (UnsupportedLookAndFeelException ex) {
                        Logger.getLogger(gui.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCariIterasi;
    private javax.swing.JButton btnCariMuller;
    private javax.swing.JButton btnCariRF;
    private javax.swing.JButton btnClearIterasi;
    private javax.swing.JButton btnClearMuller;
    private javax.swing.JButton btnClearRF;
    private javax.swing.JButton btnSimpanIterasi;
    private javax.swing.JButton btnSimpanMuller;
    private javax.swing.JButton btnSimpanRF;
    private javax.swing.JTextPane hAkhirIterasi;
    private javax.swing.JTextPane hAkhirMuller;
    private javax.swing.JTextPane hAkhirRF;
    private javax.swing.JTextField inBatasatasIterasi;
    private javax.swing.JTextField inBatasatasRF;
    private javax.swing.JTextField inBatasbawahIterasi;
    private javax.swing.JTextField inBatasbawahRF;
    private javax.swing.JTextField inErrorIterasi;
    private javax.swing.JTextField inErrorMuller;
    private javax.swing.JTextField inErrorRF;
    private javax.swing.JTextField inFxIterasi;
    private javax.swing.JTextField inFxMuller;
    private javax.swing.JTextField inFxRF;
    private javax.swing.JTextField inGxIterasi;
    private javax.swing.JTextField inIterasiIterasi;
    private javax.swing.JTextField inIterasiMuller;
    private javax.swing.JTextField inIterasiRF;
    private javax.swing.JTextField inX0Muller;
    private javax.swing.JTextField inX1Muller;
    private javax.swing.JTextField inX2Muller;
    private javax.swing.JPanel input1;
    private javax.swing.JPanel inputIterasi;
    private javax.swing.JPanel inputMuller;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JPanel output1;
    private javax.swing.JPanel output2;
    private javax.swing.JPanel outputIterasi;
    private javax.swing.JScrollPane scrollpane;
    private javax.swing.JScrollPane scrollpane1;
    private javax.swing.JScrollPane scrollpane2;
    private javax.swing.JTable tProsesIterasi;
    private javax.swing.JTable tProsesMuller;
    private javax.swing.JTable tProsesRF;
    private javax.swing.JPanel tabAitken;
    private javax.swing.JPanel tabBiseksi;
    private javax.swing.JPanel tabIterasi;
    private javax.swing.JTabbedPane tabMetode;
    private javax.swing.JPanel tabMuller;
    private javax.swing.JPanel tabNR;
    private javax.swing.JPanel tabRF;
    private javax.swing.JPanel tabSecant;
    // End of variables declaration//GEN-END:variables
}

